development:
  adapter: postgresql
  encoding: unicode
  database: surf_development
  pool: 5
  username: ciaran
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: surf_test
  pool: 5
  username: ciaran
  password:
